on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/fatina
          github-token: ${{ secrets.GITHUB_TOKEN }}
