name: ⌛ Pull Request

on:
  pull_request:
    branches: [develop]
  paths:
    - packages/**
    - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test