name: ⌛ Tests

on:
  push:
    branches: [develop]
    paths:
      - packages/**
      - yarn.lock
  pull_request:
    branches: [develop]
    paths:
      - packages/**
      - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/fatina
          path-to-lcov: packages/fatina/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
